# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: build-ios-app
on:
  push:
    branches:
      - 'Infra/#33-fastlane'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
            
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
           
      - name: Install Fastlane
        run: brew install fastlane
      
      - name: Install CocoaPods
        run: sudo gem install cocoapods
        
      - name: Match Development
        run: fastlane match development
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      - name: Run Fastlane
        run: fastlane beta
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          GIT_URL: ${{ secrets.GIT_URL }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
